### ISSUE TITLE
Question: How to set a url

### ISSUE THREAD

**Issue by CuongVoThanh** [BMW-InnovationLab/BMW-Anonymization-API#1]
Hi team, 

I read the configuration instruction but I don't know how to set_url. Could you support me for that in detail?
Thanks very much.

**Comment by JMT800** [comment]
Hello @CuongVoThanh ,
If you're deploying the inference API and the Anonymization API on different machines, then you can set the url via the post request set_url by specifying the following info "http://ip:port/". However if you're deploying both the inference and the anonymization API on the same machine, then you can specify "http://127.0.0.1:port/" or you can refer to the [docker-compose setup ](https://github.com/BMW-InnovationLab/BMW-Anonymization-API/blob/master/docker_compose_readme.md) as well. If the above does not work/help much, feel free to let us know !
